class REQUEST:
    GET_PARAM = 1
    SET_PARAM = 2

    GET_QUE_ITEM = 7
    GET_QUE_LENGTH = 8

    SET_ALLOW_CAPTURE = 9
    SET_SEND_STATES = 10
    SET_DEFAULT_ALLOW_CAPTURE = 11
    SET_DEFAULT_SEND_STATES = 12

    SHUTDOWN = 13
    GET_FILE = 14
    GET_BYTES = 15
    ENUM_DB = 16
    CLEAR_DB = 17
    UPLOAD = 18
    UNKNOWN = 19
    TRANSFER = [GET_FILE, GET_BYTES, UPLOAD]